### PR TITLE
fix: log runtime output to env var "BPFTIME_LOG_OUTPUT"

### LINKED ISSUE #279: [FEATURE] Make logs (printed from spdlog) sended to trace_pipe on agent
We should support that make logs printed from spdlog being sended to trace_pipt, not directly printed from the process injected by agent

### PR DESCRIPTION
**Pull request by Kailian-Jacy**
## Description

A draft version of logging. It implements:
- Log spdlogs to target from env var BPFTIME_LOG_OUTPUT. Default to be stderr. All logs from runtime (syscall_server, agent, agent-transformer) go to given target.
- Logs from client (cli/main.cpp) and ebpf program output untouched. I suppose ppl always want client feedback from stdout/err.

Used file but not named pipe. bpftime server should be similar to docker daemon, managing "services" of injected ebpf programs. The log should be persistent, reusable. 

Now usage:
```
kailian@ubt23:~/bpftime$ sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime load ./example/opensnoop/opensnoop\
PID    COMM              FD ERR PATH
^CINFO [40749]: Global shm destructed

kailian@ubt23:~/bpftime$ cat skeleton_logging.out
[2024-06-02 10:12:32][info][40749] manager constructed
[2024-06-02 10:12:32][info][40749] Initialize syscall server
[2024-06-02 10:12:32][info][40749] Global shm constructed. shm_open_type 0 for bpftime_maps_shm
[2024-06-02 10:12:32][info][40749] Global shm initialized
[2024-06-02 10:12:32][info][40749] Enabling helper groups ufunc, kernel, shm_map by default
[2024-06-02 10:12:32][info][40749] bpftime-syscall-server started
```

I may add these feature in this PR, hoping suggestions or confirmation from you:

- Provide a subcommand similar to trace to output logs we want.
- Logs be optionally reserved under /var/log/ or syslog under linux. Log rotation are management automatically.
- Merge logs from different processes as one. Add tags of source (which injected process causing) to the log. 
- Add documentations about logging. 

resolves # 279

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Manually test: load & start.

```
sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime load ./example/opensnoop/opensnoop
sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime start  ./example/opensnoop/victim
sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime start  -s ./example/opensnoop/victim
```

- [x] Manually test: load & attach.

```
sudo BPFTIME_LOG_OUTPUT=victim_out.log ./example/opensnoop/victim
sudo BPFTIME_LOG_OUTPUT=skeleton_logging.out /home/kailian/.bpftime/bpftime -i /home/kailian/.bpftime attach `pidof victim`
```

**Test Configuration**:

- Hardware: x86
- Toolchain:g++
- OS: ubuntu 23.10

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by yunwei37** [comment]
Also:

1. Fix compile for build without libbpf in Linux
2. Add option build test in CI

File: runtime/include/bpftime_logger.hpp [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+inline std::string expand_user_path(const std::string &input_path)
+{
+	if (input_path.empty()) {
+		return "console";
+	}
+
+	if (input_path[0] == '~') {
+		const char *homeDir = getenv("HOME");
+		if (!homeDir) {
+			return "console";
```
Comment (Officeyutong) [inline runtime/include/bpftime_logger.hpp:23]: Will string "console" be parsed as a path?

File: runtime/include/bpftime_config.hpp [hunk 2]
```diff
@@ -4,6 +4,11 @@
 #include <cstdlib>
 #include <string>
 
+#ifndef DEFAULT_LOGGER_OUTPUT_PATH
+#define DEFAULT_LOGGER_OUTPUT_PATH "~/.bpftime/runtime.log"
```
[the remark this answers is not in the document]
Comment (yunwei37) [reply runtime/include/bpftime_config.hpp:8]: Ok, I can fix that in next pr

File: runtime/include/bpftime_logger.hpp (hunk 1 above)
Comment (yunwei37) [reply runtime/include/bpftime_logger.hpp:23]: Yes, to stderr. The console log output will also be used in CI

Comment (Officeyutong) [reply runtime/include/bpftime_logger.hpp:23]: > Yes, to stderr. The console log output will also be used in CI

I mean, if user want to print things to a file named `console`

Comment (yunwei37) [reply runtime/include/bpftime_logger.hpp:23]: That might still be print to the console...Any suggestion for handling this case?

File: runtime/include/bpftime_config.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (yunwei37) [reply runtime/include/bpftime_config.hpp:8]: The problem is that it might be input by the cmake... is it better to 
```c
#ifndef DEFAULT_LOGGER_OUTPUT_PATH
const char* default_log_path =  "~/.bpftime/runtime.log"
#else    
const char* default_log_path =  DEFAULT_LOGGER_OUTPUT_PATH
#endif
```
I think the old one is  a straightforward and clean way to ensure that a default value is set if none is provided.

File: runtime/include/bpftime_logger.hpp (hunk 1 above)
Comment (Officeyutong) [reply runtime/include/bpftime_logger.hpp:23]: For example, use std::optional<string> as the return type of this function. If $HOME is not set, returning empty optional
